:Author: JoyceChin
:Email: chinjoyce30@gmail.com
:Date: 1/03/2017
:Revision: version#
:License: Public Domain

= Project: {Flash and Music}

Describe your project

== Step 1: Installation




1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram Music.png, Flash.jpg attached to the sketch


== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 Flash_and_Music                => Arduino sketch folder
  ├── Flash_and_Music.ino       => main Arduino file
  ├── Music.png      => (optional) an image of the required schematics
  ├── Flash.jpg          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {Punlic Domain} License.

=== Contributing
To contribute to this project please contact JoyceChin <chinjoyce30@gmail.com>

=== BOM
Add the bill of the materials you need for this project.

|===
| | Part name         | Quantity
| | Arduino UNO R3    | 1        
| | buzzer            | 1          
| | DuPont line       | 9
| | speaker 8ohm      | 1
| | resistance        | 7
| | LED               | 6
| | DuPont line       | 9

    
|===



